version: '3'

services:

  golang-grpc-server:
    build:
      context: .
      dockerfile: ./name_resolving/server/Dockerfile
    command: go run main.go
    volumes:
    - ../:/go/src/app
    working_dir: /go/src/app
    environment:
      PORT: 50051
    networks:
      grpc_net:
        ipv4_address: ${server_ip}

  golang-grpc-client:
    build:
      context: .
      dockerfile: ./name_resolving/client/Dockerfile
    command: go run main.go
    volumes:
    - ../:/go/src/app
    working_dir: /go/src/app
    environment:
      PORT: 50051
    networks:
      grpc_net:
    depends_on:
      - golang-grpc-server

networks:
  grpc_net:
    ipam:
      driver: default
      config:
        - subnet: ${subnet_ip_mask}