version: '3.2'

services:

  etcd-1:
    container_name: etcd1
    image: quay.io/coreos/etcd:v3.1.20
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://etcd-1:2380'
      - '--listen-client-urls=http://etcd-1:2379,http://localhost:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 2379
    volumes:
      - etcd1:/etcd_data
    networks:
      grpc_net:
        #ipv4_address: ${etcd_1_server_ip}

  etcd-2:
    container_name: etcd2
    image: quay.io/coreos/etcd:v3.1.20
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://etcd-2:2380'
      - '--listen-peer-urls=http://etcd-2:2380'
      - '--listen-client-urls=http://etcd-2:2379,http://localhost:2379'
      - '--advertise-client-urls=http://etcd-2:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 2379
    volumes:
      - etcd2:/etcd_data
    networks:
      grpc_net:
        #ipv4_address: ${etcd_2_server_ip}
    depends_on:
      - etcd-1

  etcd-3:
    container_name: etcd3
    image: quay.io/coreos/etcd:v3.1.20
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://etcd-3:2380'
      - '--listen-peer-urls=http://etcd-3:2380'
      - '--listen-client-urls=http://etcd-3:2379,http://localhost:2379'
      - '--advertise-client-urls=http://etcd-3:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - 2379
    volumes:
      - etcd3:/etcd_data
    networks:
      grpc_net:
        #ipv4_address: ${etcd_3_server_ip}
    depends_on:
      - etcd-1
      - etcd-2

  golang-grpc-server:
    container_name: golang-grpc-server
    build:
      context: .
      dockerfile: ./wonaming/example/server/Dockerfile
    ports:
      - 2379
      - 1701
    command: go run main.go
    volumes:
    - ../:/go/src/app
    working_dir: /go/src/app
    environment:
      PORTS: 2379
    networks:
      grpc_net:
        #ipv4_address: ${server_ip}
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3


  golang-grpc-client:
    build:
      context: .
      dockerfile: ./wonaming/example/client/Dockerfile
    ports:
      - 2379
      - 1701
    command: go run main.go
    volumes:
    - ../:/go/src/app
    working_dir: /go/src/app
    environment:
      PORTS: 2379
    networks:
      grpc_net:
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
      - golang-grpc-server

networks:
  grpc_net:
    #ipam:
      #driver: default
      #config:
        #- subnet: ${subnet_ip_mask}

volumes:
  etcd1:
  etcd2:
  etcd3: